### ISSUE TITLE
Supply parameters for functions?

### ISSUE THREAD

**Issue by headwindfly** [cbroglie/mustache#10]
In go mustache templates one of the examples showed how to retrieve Name1 function value into mustache template. But Name1 didn't have any parameters. Can I somehow use functions that have to receive parameters?  Is there some other way to get same results?

**Comment by cbroglie** [comment]
@headwindfly No, it's not possible to pass parameters to functions. You must use a function with arity 0.

**Comment by headwindfly** [comment]
Thanks for your reply.

I am looking for a solution about **i18n**.

For examples, I passed Locale(**map[string]string**) struct to the view.

```
Locale := map[string]string{
     "login":"Sign in",
     "logout":"Sign out",
}
```

It works in **html/template**: ` {{ .Locale "logout" }}`

But it is infeasible in mustache.

Is it possible to add support for passing parameters to function in the future? Or are there any other solutions for **i18n**?

**Comment by cbroglie** [comment]
@headwindfly That's perfectly feasible, you just need to use the correct mustache syntax:

```go
package main

import (
       	"fmt"

       	"github.com/cbroglie/mustache"
)

func main() {
       	fmt.Println(mustache.Render("{{logout}}", map[string]interface{}{"logout": "Sign out"}))
}
```

```
$ go run main.go
Sign out <nil>
$
```

**Comment by headwindfly** [comment]
@cbroglie Thanks, this is indeed an alternative way.
That will be useful if mustache supports pass parameters to function. :)

**Comment by cbroglie** [comment]
I don't expect that to be added to the official mustache spec (https://mustache.github.io/), mustache is intentionally kept simple

**Comment by headwindfly** [comment]
Ok, I understand that, anyway, thanks a lot.
