### ISSUE TITLE
Miss render on `&` char (golang)

### ISSUE THREAD

**Issue by ridhoperdana** [cbroglie/mustache#21]
I am trying to render an URL using Render function on mustache (golang). When I try to render this `http://example.com?param1=1&param2=2` the result is `http://example.com?param1=1&amp;param2=2`

The template I use is like this:
```
map[string]string{
   "URL":"http://example.com?param1=1&param2=2",
}
```
The text I want to render is like this:
`I want to access this url={{URL}}`

Am I not using the function correctly? Thanks inadvance

**Comment by cbroglie** [comment]
By default, mustache will escape characters inside of `{{ }}` blocks. You can disable the escaping by using triple brackets:
```
I want to access this url={{{URL}}}
```
