### ISSUE TITLE
Consider releasing a tagged version

### ISSUE THREAD

**Issue by ofpiyush** [cbroglie/mustache#22]
Love the work you are doing!

Can you please release a tagged version so that depending on this lib becomes easier <3

**Comment by cbroglie** [comment]
Hi @ofpiyush, can you elaborate on why you need version tags? Most Go projects don't rely on tags, but instead vendor their dependencies.

**Comment by ofpiyush** [comment]
@cbroglie vendoring makes for a really fat repo.

Code review on PRs becomes more difficult.

If I'm trying to use certain parts of a vendored repo, I end up getting type conflicts.

With tools like dep, it becomes easier to follow versioned tags.

Versioning is becoming [the new normal](https://dave.cheney.net/2016/06/24/gophers-please-tag-your-releases)

**Comment by cbroglie** [comment]
Ok, you sold me. Just pushed v1.0.0.
