### ISSUE TITLE
Feature request: Metadata methods for Template type

### ISSUE THREAD

**Issue by sebastianst** [cbroglie/mustache#3]
I suggest that we add `*Template` methods that return useful metadata about the rendered template, e.g.
```go
func (*Template) GetVariables() []string {
    // return array of variables
}

func (*Template) GetSections() []strings
```
which could loop over the `elems` array of the `Template` that was produced by `parse()` and extract the unique list of variables and sections. Similarly, `getTags()` could return some sort of nested structure of sections with their variables.

What do you think?

**Comment by cbroglie** [comment]
Would you mind providing an example template and specifying what you would expect `GetTags` and `GetSections` to return given that example? Just want to be sure I understand the ask.

**Comment by sebastianst** [comment]
Sure. Template file `template.mustache`:
```
Color={{color}}
Size={{size}}
```
Parse it, get list of tags:
```go
t, _ := mustache.ParseFile("template.mustache")
tags := t.GetTags() // Holds ["color", "size"]
```
Now the `tags []string` contains the two strings `"color"` and `"size"`.

**Comment by cbroglie** [comment]
What about a template with sections? Consider this example:
```mustache
{{#repo}}
  <b>{{name}}</b>
{{/repo}}
```

Just trying to understand if you want all the tags or just the variable ones.

**Comment by sebastianst** [comment]
Sorry, I mixed up the definition of a tag which made my idea unclear. Of course, both sections and variables are called tags. I'll edit my above comments accordingly.

I imagine that in your example, `GetVariables()` would only return`["name"]` and `GetSections()` would return `["repo"]`. There could be another method `GetTags()` that could return the tree structure of sections and tags together in some sensible way.

**Comment by cbroglie** [comment]
OK, that sounds reasonable to me. I can probably get to it within a week or so, but PRs are always welcome too.

**Comment by sebastianst** [comment]
Nice. I could probably work on it next week. Methods `GetVariables()` and `GetSections()` should be an easy iteration over `elems`.

What do you think would be a good return format for `GetTags()`? Any ideas about other metadata that could be generated for a template?

**Comment by cbroglie** [comment]
@sebastianst I opened #4, let me know if that will cover your needs

**Comment by sebastianst** [comment]
The `Tags()` method meets all my needs, thanks a lot! :)
