### ISSUE TITLE
Print JSON data structures as a value using CLI

### ISSUE THREAD

**Issue by metmajer** [cbroglie/mustache#31]
Hi, and thanks for maintaining this great project! I am trying to find a way to present random JSON data structures in an HTML file that is rendered using the `mustache` CLI.

Given the following example:
```
["a", "b"]
```

...I'd like to see the following ]results:
```
["a", "b"]
```

...but get:
```
[a b]
```

in the resulting document. Any ideas on how to achieve this goal? Thanks!

**Comment by cbroglie** [comment]
Hi @metmajer, to make sure I understand the ask, can you please share a small example program that demonstrates the issue?

**Comment by metmajer** [comment]
Hi @cbroglie, and thanks for your reponse. Sure, here's a reproducible example:

File: data.js
```
{
    "data": {
        "a": [],
        "b": ["foo", "bar"],
        "c": "baz"
    }
}
```

File: index.html.tmpl
```
<h1>Data</h1>

<p>
{{ data }}
</p>

<p>
{{{ data }}}
</p>
```

Finally, `mustache data.js index.html.tmpl` yields:

```
<h1>Data</h1>

<p>
map[a:[] b:[foo bar] c:baz]
</p>

<p>
map[a:[] b:[foo bar] c:baz]
</p>
```

I am using `v1.0.1`.

**Comment by cbroglie** [comment]
AFAIK there is nothing in the mustache spec that says it should automatically output JSON here. If you want to output JSON, then you should call `json.Marshal` on the data before passing it to mustache.

**Comment by metmajer** [comment]
Agreed, the spec doesn't say so. But as I stated in the title, I am using the CLI, and not a controller implementation for the moment.

If you're accepting JSON as a data input format, as a user I'd expect you to support this in the output as well -- at least when I want to dump a nested data structure.

**Comment by cbroglie** [comment]
No, mustache implementations output the default string representation of the given data, which varies by language (e.g. the JS version will output `[object Object]`). It's your job to fit the template to the data.
