### ISSUE TITLE
Treating default (zero) as falsy values

### ISSUE THREAD

**Issue by arjunmayilvaganan** [cbroglie/mustache#42]
Is the below the expected behaviour?
https://play.golang.org/p/FcnoGnJlwLv

I saw https://github.com/cbroglie/mustache/pull/33 and it makes me think otherwise

**Comment by cbroglie** [comment]
I think your example is using an older version of the library b/c I hadn't tagged a release since #33 was merged. I've now tagged v1.1.0; with that version you should see the expected behavior.

**Comment by arjunmayilvaganan** [comment]
Thank you so much, Broglie.
