### ISSUE TITLE
Error: unknow flag: --layout

### ISSUE THREAD

**Issue by georgebias** [cbroglie/mustache#46]
Hi,

I'm trying to run the command below:

`mustache sosrecarga.json templates/sosrecarga/home.mustache --layout templates/sosrecarga/layout.mustache`

And he returns this error to me:

`Error: unknow flag: --layout`

**Comment by cbroglie** [comment]
This is b/c I hadn't tagged a new release since the flag was implemented. It's now available: https://github.com/cbroglie/mustache/releases/tag/v1.2.0.
