### ISSUE TITLE
dot-notation for nested data..method output map -> map key?

### ISSUE THREAD

**Issue by cathalgarvey** [cbroglie/mustache#5]
Hey cbroglie, thanks for taking over maintenance of this great lib, it seems that your and [@jabley's](/jabley/mustache) forks are the two most developed since @hosie's went quiet.

I'm just developing something using the original hosie code, and I've noticed it doesn't appear to do nested queries using dot-notation. I think [@Wuvist](/Wuvist/mustache/commit/948a0458168b6819ec0d5f6073b4f2b81e31937d) added this feature in his fork, I'm wondering whether you could pull from his, and I could switch to using your repo?

It's a pity something that got so many fans and forks got abandoned, there are lots of forks pushing some great features but not enough cohesion. :(

**Comment by cbroglie** [comment]
I recently pushed 8c0c2fe, which tests this repo against https://github.com/mustache/spec for compliance. While a number of tests fail currently, the dot notation tests are generally passing. Do you have a test case which demonstrates the missing functionality?

**Comment by cathalgarvey** [comment]
:bangbang: gorramn I found my problem, and it's kinda PEBKAC. So, you're right; map access can be dotted after method receivership and that works fine. My problem, it turns out, is that only the first object with a matching method is tested for a valid key, whereas I had thought mustache would do a more in-depth search through the context list.

Code:

`go
package main

import "github.com/hoisie/mustache"

var template = `
---
Here is the map entry for "foo": {{TemplateData.foo}}
Here is some other top-level "foo": {{foo}}
---
`

type MapGiver struct {
	underlyingMap map[string]string
}

func (mg MapGiver) TemplateData() map[string]string {
	return mg.underlyingMap
}

func main() {
	mg := new(MapGiver)
	mg.underlyingMap = make(map[string]string)
	mg.underlyingMap["foo"] = "Bar"
	mg2 := new(MapGiver)
	mg2.underlyingMap = make(map[string]string)
	otherMap := make(map[string]string)
	otherMap["foo"] = "baz"
	win := mustache.Render(template, mg, otherMap)
	fail := mustache.Render(template, mg2, mg, otherMap)
	println(win)
	println(fail)
}
`

Now I need to rethink my program design, because I was hoping to create a system where all "optional" template data was gated behind "TemplateData" methods on context objects, and only "crucial/core" data was directly accessible from an interface object. Hmmm.

Thanks anyway, my mistake!
