### ISSUE TITLE
Remove `golangci-lint` from `go.mod`

### ISSUE THREAD

**Issue by iredmail** [cbroglie/mustache#57]
Dear developers,

If i understand correctly, you can always run `golangci-lint` from command line (or GitHub Actions), but no need to include it as a dependent package in `go.mod`. Is it possible to remove it from `go.mod` and make the dependent packages minimalist? :)

I generated a relationship map of dependent packages for gofiber/template which involves mustache as a supported html template engine, it's quite interesting:

https://github.com/gofiber/template/issues/117

**Comment by cbroglie** [comment]
It's a reasonable request, vendoring golangci-lint was just the easiest way for me to get CI working years ago. I'm open to a PR.

**Comment by iredmail** [comment]
FYI, golangci-lint as GitHub Actions: https://github.com/marketplace/actions/run-golangci-lint

**Comment by iredmail** [comment]
Dear @cbroglie 

I’d like to send a PR, but is file “tools.go” still required? I’m not sure whether removing it affects other parts of the project. 

Could you help remove golangci-lint from go.mod since you’re more familiar with the whole CI flow?
