### ISSUE TITLE
How do you set new delimiters?

### ISSUE THREAD

**Issue by NathanClassen** [cbroglie/mustache#61]
The documentation says that changing delimiters is a supported feature, but I am not seeing how to set new delimiters?

Is there a method for this? The Template type is all un-exported so one cannot create a template and set the tags that way either.

**Comment by cbroglie** [comment]
You set the delimiter in the template itself, not the code. See the `Set Delimiter` section of https://mustache.github.io/mustache.5.html.

**Comment by NathanClassen** [comment]
Ah, I see. I am coming from a Java Mustache engine that let you set the delimiters on the engine itself.

Thanks for the response!
