### ISSUE TITLE
Updated steps for installing CLI

### ISSUE THREAD

**Issue by sandeepantony** [cbroglie/mustache#71]
Looks like the 'go get github.com/cbroglie/mustache/...' is deprecated now. Could you help me by providing the updated command to install the cli wrapper?

**Comment by jornh** [comment]
That's correct if you're on Go 1.17 or later: https://go.dev/doc/go-get-install-deprecation 

Now you can:
``` bash
go install github.com/cbroglie/mustache/cmd/mustache@v1.3.0  # for a specific version - or @latest 
```

**Comment by sandeepantony** [comment]
thank you!

**Comment by cbroglie** [comment]
Thanks @jornh, I'll update the README
