### ISSUE TITLE
Command-line binary?

### ISSUE THREAD

**Issue by fidian** [cbroglie/mustache#9]
Is there any chance that there would be a standalone binary that could be used from command line?

I'm envisioning something like this:

    mustache data.yaml template.mustache > result.txt

I wouldn't imagine HTML escaping would be enabled, but maybe that would be controlled by an option passed to the program.

Would such a thing be difficult?  Does this already exist?

**Comment by cbroglie** [comment]
Hey @fidian, this would be easy to implement, but it would have to be a standalone project which leveraged this package, since a folder cannot contain both a package and be main in Go.

**Comment by fidian** [comment]
Well, seeing how it can't go in this project I will close this request.

I do appreciate the speedy response.  It looks like one of my coworkers might learn Go to implement this command line tool in the near future ... unless someone else beats him to it.
